# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100

    IGNR_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

IGNR_controller:
  ros__parameters:
    joints:
      - base_link_to_rotator1
      - pivot1_to_arm1
      - arm1_to_pivot2
      - pivot2_to_arm2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
